### ISSUE TITLE
slow page loads

### ISSUE THREAD

**Issue by gixxy22** [engram-design/CPNav#100]
when cpnav is enabled, it adds ~300ms to each page load in admin. currently around 900ms for a page load, when disabling cpnav it drops to ~600ms.

anything thats causing this?

**Comment by engram-design** [comment]
Well, there's a lot more overhead with generating the menu, mostly because Craft needs to generate the menu first, then CP Nav takes over with database calls to its own tables to fetch your custom nav items (order, names, etc), so there's always going to be some overhead. It probably shouldn't be as high as 300ms, but it also doesn't surprise me.

I'll take a look at some ways we can improve performance.

**Comment by engram-design** [comment]
Should be improved in [4.0.0-beta.2](https://github.com/verbb/cp-nav/releases/tag/4.0.0-beta.2) for Craft 4.
