### ISSUE TITLE
After updating to Craft 4, existing plugins don't show sub-nav items at all

### ISSUE THREAD

**Issue by darylknight** [engram-design/CPNav#105]
**Description**
Looks like a new section was added in Craft 4:

![image](https://user-images.githubusercontent.com/1250017/175523065-f653baf9-dc10-480f-b144-a6b64f69e5a4.png)

This means that all existing plugins (specifically Freeform for us) do not have any subnav items until you reset the navigation.

**Steps to reproduce**
1. Update to Craft 4
2. Plugin sub-nav items are not available until you reset the navigation

**Additional info**
- Plugin version: 4.0.2
- Craft version: 4.0.5.1
- Multi-site: No

**Comment by darylknight** [comment]
Additionally, I actually reset the navigation locally, committed it all and deployed, but the staging server still does not have the sub-navigation items under freeform, even though they're working on the local version of the site.

**Comment by engram-design** [comment]
Are you saying you upgraded from Craft 3 to Craft 4? If so, then you'll likely need to reset the navigation, because there were a few architectural changes (this is one of them). We try to take care of it, but it's not 100% foolproof, as it's a bit complex. I'll see if we can handle subnav items better.

Or - are you saying that subnav items aren't appearing anyway, after installing a plugin like Freeform (and you've been on Craft 4 already).

As for the nav items on staging, can you check the `cpnav_navigation` database table? You _should_ be seeing items in there with different `level` values.

**Comment by darylknight** [comment]
I meant that I upgraded from Craft 3 to Craft 4, and afterwards, plugins do not have sub-nav items. If it's expected that we'll need to reset the navigation rather than it getting migrated, that's fine - I just thought I'd point it out in case it wasn't intended.

I deleted my second commend about the staging site - looks like the deployment failed. However, after uninstalling, deploying, reinstalling, deploying, then updating the navigation and deploying again - it looks like the staging server still isn't showing the correct navigation.

Here's the settings on the local site:

![image](https://user-images.githubusercontent.com/1250017/175525338-c7523ae9-54d8-4f3a-80eb-400410c8b3a2.png)

And here's what's appearing under Freeform on the staging server:

![image](https://user-images.githubusercontent.com/1250017/175525374-bd90bb4c-b7b3-48c9-ba6e-7db1f119e63e.png)

And here's the cpnav_navigation table:

![image](https://user-images.githubusercontent.com/1250017/175525505-ae7fb960-9cf1-4b9e-8f95-e9825bde1e0b.png)

**Comment by engram-design** [comment]
So it _should_ be handling subnav items during the migration, so I'll look into it.

The issue _could_ be that the subnav items are out of order in the database, but I don't think that should matter. I'll see if I can replicate it. It looks like they're missing their `parentId`, probably because they're imported first.

**Comment by scandella** [comment]
Same issue after upgrading from Craft 3.
Resetting the navigation did not resolve the issue.
I had to set a value for the "Default Subnav Behavior" to have the submenu working again.
So it seems that the "Default Subnav Behavior" have no value after the Craft upgrade.

**Comment by engram-design** [comment]
Fixed in [4.0.4](https://github.com/verbb/cp-nav/releases/tag/4.0.4)
