### ISSUE TITLE
Craft3 error

### ISSUE THREAD

**Issue by Delonvdv** [engram-design/CPNav#32]
### Description
The plugin looks like it installed properly but when I go into setting it see the following:
Database Exception – yii\db\Exception
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'staging.craft_cpnav_layout' doesn't exist
The SQL being executed was: SELECT *
FROM `craft_cpnav_layout`
Error Info: Array
(
    [0] => 42S02
    [1] => 1146
    [2] => Table 'staging.craft_cpnav_layout' doesn't exist
)
↵
Caused by: PDOException
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'staging.craft_cpnav_layout' doesn't exist
in /pathToMyProject/craft/vendor/yiisoft/yii2/db/Command.php at line 1067

### Steps to reproduce

1. I used the Plugin Store to install.
2.

### Additional info

- Plugin version: 2.0.2
- Craft version: Craft Pro 3.0.0-RC3

**Comment by engram-design** [comment]
Can't seem to replicate this, and sounds like a problem with the installation. This seems like it might've been an upgrade from a Craft 2 site? It does sound like the database table for CPNav is missing, are you able to confirm this?

**Comment by Delonvdv** [comment]
Hi it was an upgrade from from Craft 2 to 3. I dont remember exactly how I fixed it but I believe I ran the update again, but on RC 4 or 5 and it all worked as expected.

**Comment by engram-design** [comment]
Closing as this has seemingly been fixed.

**Comment by phelgren** [comment]
This one bit me as well and I am currently trying to work through it.  Situation is that I upgraded from Craft 2 to 3.4.5.  Clicked all the was through finish.  Signed in and started the process of installing the plugins that I had before.  Control Panel Nav was the first plugin I chose.  Plugin install failed because curl cacert.pem file was missing or out of date.  Got the correct file.  Installed it in php.  Restarted Apache and  now I see:

`Database Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'marketing.craft_cpnav_layout' doesn't exist
The SQL being executed was: SELECT *
FROM craft_cpnav_layout

Migration: verbb\cpnav\migrations\m200119_000000_permissions_uid

Output:

Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'bsf_marketing.craft_cpnav_layout' doesn't exist
The SQL being executed was: SELECT *
FROM craft_cpnav_layout (E:\Craft_3\vendor\yiisoft\yii2\db\Schema.php:674)
`
I'll continue to try to fix this manually but a pointer might be helpful. haven't dug deep but Craft is DOA at the moment.  Running Windows 10, Apache 2.4.33, PHP  7.2.27, Maria DB 10.2

**Comment by engram-design** [comment]
@phelgren I've had a few people report this now, so going to reopen.

I would assume you had CP Nav installed and configured on Craft 2? Not sure about the pem file error (I'd say that's unrelated). I think this might be a specific Craft 2 > 3 upgrade issue

**Comment by phelgren** [comment]
Yes, cpnav was installed on v2.0  The only reason I mentioned the pem file error is that is would have interrupted the update from completing?  Maybe not.  What I ended up doing was a DB table hack to get the correct tables and columns into the DB.  Once the tables were correct, the install completed fine.

**Comment by engram-design** [comment]
Should be fixed in [3.0.4](https://github.com/verbb/cp-nav/releases/tag/3.0.4)
