### ISSUE TITLE
"Control Panel Layout" field type

### ISSUE THREAD

**Issue by lindseydiloreto** [engram-design/CPNav#7]
Just wondering, what is the purpose of the Control Panel Layout field type?

On a similar note, I don't like that an actual field was automatically created for me. Is this necessary? It doesn't seem to be necessary... I deleted the field, and the plugin still works fine otherwise.

**Comment by lindseydiloreto** [comment]
After deleting the Control Panel Layout field, I tried to uninstall the plugin and it crashed. So I tried to create a new Control Panel Layout field, and it's not possible. Looks like I've got to roll back my database to before the plugin was installed.

I'd love to know the reasoning behind needing a Control Panel Layout field type... In my mind, it's not necessary, and introduces a lot of complications.

**Comment by engram-design** [comment]
The field is used to allow your users to define their own menu (to a degree) as described [here](https://github.com/engram-design/CPNav#user-layout) and in further details in [#1](https://github.com/engram-design/CPNav/issues/1).

The field is added for you, because I didn't want users to be able to add this field to anywhere but the user profile. I also didn't want people to be able to add more than one layout field (I don't know what would happen, but the universe would likely explode).

As for the reasoning, it's all about creating navigation layouts per-user. Say you have a client account and your admin account. Currently, if you want to alter the CP navigation, it'll affect your admin account's navigation, which is okay - but not ideal. There are sections that you might wish your client not to be able to access, but the admin to still be able to.

I'm going to put together a more comprehensive troubleshooting section, but it'll fix itself if you delete any `cpnav_` tables, along with deleting the CPNav row in `craft_plugins` which will essentially uninstall the plugin.

I'll admit, the field type doesn't really solve the issue that elegantly. I'm working on a better solution!

**Comment by lindseydiloreto** [comment]
"... the universe would likely explode..." Lol!

Hmm, that's quite a conundrum. I can see the logic issues behind the problem, you make some really good points.

For me personally, I'll be using the plugin on sites **without users** about 60-70% of the time. In that case, it just becomes an extraneous field with no real purpose (and can't safely be deleted).

It's definitely a tricky situation... If I come up with any clever suggestions, I'll let you know! :)

**Comment by engram-design** [comment]
I think we're both on the same page though. I think i'll add the option to opt-in to this, rather than have it always on. That and you should be able to safely delete it.

What I'm planning is complete control through the plugin itself. You'll be able to create different layouts (one for Admin, one for Client, one for Users, etc), each of which you can allocate to a user. This solves the 'user' issue for Craft Pro - which doesn't allow a user Profile, but still has 'multiple' users.

For the moment - just don't delete that field type just yet. Or comment the lines `$this->addFieldToUserProfile();` and `$this->removeFieldToUserProfile();` out of `CpNavPlugin.php`.

**Comment by lindseydiloreto** [comment]
Great workaround, thanks Josh!

Perhaps it would make sense for the plugin to detect if Craft Pro is licensed, and only add the field in that case. Of course, you'd also need to add the field in the case of someone _upgrading_ to Craft Pro. (I don't think there is an event yet for "onEditionChange"... I'll add it as a formal feature request.)

**Comment by lindseydiloreto** [comment]
[Feature requested!](http://feedback.buildwithcraft.com/forums/285221-feature-requests/suggestions/7278300-add-an-event-for-oneditionchange)

**Comment by engram-design** [comment]
Nice one, upvoted! I'm unsure about the future of the field type, so we'll see :)

**Comment by lindseydiloreto** [comment]
Woohoo! It's been added in Craft 2.4...

http://buildwithcraft.com/docs/plugins/events-reference#onEditionChange

**Comment by engram-design** [comment]
@lindseydiloreto people power! Working on a whole reworked version of this at the moment, which won't use the field type. Notably, the field type doesn't exist anymore, and won't be used in the future.

**Comment by lindseydiloreto** [comment]
Lol, that's what I figured. No worries though, `onEditionChange` is still a great event to have.
