### ISSUE TITLE
Which layout applies for users in multiple groups?

### ISSUE THREAD

**Issue by KatieMFritz** [engram-design/CPNav#73]
I'm using granular user groups (blog editor, courses editor, etc.) and some users are in multiple groups.

How does cp-nav know which layout to use for a user? 

Would the best way to handle this be creating unique user groups for each layout isntead?

**Comment by ademers** [comment]
I have the same question.

**Comment by engram-design** [comment]
Yep, so the best course of action is to create a user group for the layout and apply that. Otherwise, you'll get the first layout for the matching group, in order of when you created the group.

So if you have a user, who belongs to "Group 1" and "Group 2" (created in that order). You have a layout setup for each of these groups, but the CP Nav they'll see will always be the layout for Group 1.
